// @generated by protobuf-ts 2.9.4 with parameter long_type_string
// @generated from protobuf file "account.proto" (package "account", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AccountService } from "./account";
import type { UpdateProfileResponse } from "./account";
import type { UpdateProfileRequest } from "./account";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetProfileResponse } from "./account";
import type { EmptyRequest } from "./account";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service account.AccountService
 */
export interface IAccountServiceClient {
    /**
     * @generated from protobuf rpc: GetProfile(account.EmptyRequest) returns (account.GetProfileResponse);
     */
    getProfile(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, GetProfileResponse>;
    /**
     * @generated from protobuf rpc: UpdateProfile(account.UpdateProfileRequest) returns (account.UpdateProfileResponse);
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, UpdateProfileResponse>;
}
/**
 * @generated from protobuf service account.AccountService
 */
export class AccountServiceClient implements IAccountServiceClient, ServiceInfo {
    typeName = AccountService.typeName;
    methods = AccountService.methods;
    options = AccountService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetProfile(account.EmptyRequest) returns (account.GetProfileResponse);
     */
    getProfile(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, GetProfileResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, GetProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateProfile(account.UpdateProfileRequest) returns (account.UpdateProfileResponse);
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, UpdateProfileResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateProfileRequest, UpdateProfileResponse>("unary", this._transport, method, opt, input);
    }
}
